/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client04)
#  Generated on:      Wed Nov 13 23:19:08 2019
#  Design:            screen_design
#  Command:           saveNetlist screen_design_post_opt_netlist_innovus.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 13 2019 23:10:31 IST (Nov 13 2019 17:40:31 UTC)
// Verification Directory fv/screen_design 
module pixel_itr (
	clk, 
	rst, 
	pix_x, 
	pix_y, 
	h_sync, 
	v_sync, 
	draw_active, 
	screen_end, 
	draw_end);
   input clk;
   input rst;
   output [11:0] pix_x;
   output [11:0] pix_y;
   output h_sync;
   output v_sync;
   output draw_active;
   output screen_end;
   output draw_end;

   // Internal wires
   wire [11:0] v_pos;
   wire [11:0] h_pos;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;

   NOR4BBXL g1081 (.AN(v_pos[9]),
	.BN(n_141),
	.C(v_pos[8]),
	.D(n_111),
	.Y(v_sync));
   NOR2BXL g1082 (.AN(v_pos[5]),
	.B(n_110),
	.Y(pix_y[5]));
   OR2X1 g1083 (.A(v_pos[6]),
	.B(n_110),
	.Y(pix_y[6]));
   NOR2BXL g1084 (.AN(v_pos[7]),
	.B(n_110),
	.Y(pix_y[7]));
   NOR2BXL g1085 (.AN(v_pos[8]),
	.B(n_110),
	.Y(pix_y[8]));
   NOR2BXL g1086 (.AN(v_pos[3]),
	.B(n_110),
	.Y(pix_y[3]));
   OR2X1 g1087 (.A(v_pos[0]),
	.B(n_110),
	.Y(pix_y[0]));
   OR2X1 g1088 (.A(v_pos[1]),
	.B(n_110),
	.Y(pix_y[1]));
   OR2X1 g1089 (.A(v_pos[2]),
	.B(n_110),
	.Y(pix_y[2]));
   OR2X1 g1090 (.A(v_pos[4]),
	.B(n_110),
	.Y(pix_y[4]));
   AOI32XL g1091 (.A0(n_139),
	.A1(n_97),
	.A2(n_99),
	.B0(n_108),
	.B1(v_pos[7]),
	.Y(n_111));
   NAND2XL g1092 (.A(n_97),
	.B(n_109),
	.Y(n_110));
   OAI31XL g1093 (.A0(v_pos[8]),
	.A1(v_pos[7]),
	.A2(n_105),
	.B0(v_pos[9]),
	.Y(n_109));
   NOR2XL g1094 (.A(n_102),
	.B(n_107),
	.Y(h_sync));
   NOR4XL g1095 (.A(v_pos[5]),
	.B(v_pos[4]),
	.C(v_pos[3]),
	.D(n_103),
	.Y(n_108));
   OA22X1 g1096 (.A0(h_pos[7]),
	.A1(n_104),
	.B0(h_pos[6]),
	.B1(n_101),
	.Y(n_107));
   AND2X1 g1097 (.A(h_pos[1]),
	.B(n_106),
	.Y(pix_x[1]));
   AND2X1 g1098 (.A(h_pos[3]),
	.B(n_106),
	.Y(pix_x[3]));
   AND2X1 g1099 (.A(h_pos[4]),
	.B(n_106),
	.Y(pix_x[4]));
   AND2X1 g1100 (.A(h_pos[2]),
	.B(n_106),
	.Y(pix_x[2]));
   AND2X1 g1101 (.A(h_pos[7]),
	.B(n_106),
	.Y(pix_x[7]));
   AND2X1 g1102 (.A(h_pos[0]),
	.B(n_106),
	.Y(pix_x[0]));
   AND2X1 g1103 (.A(h_pos[5]),
	.B(n_106),
	.Y(pix_x[5]));
   AND2X1 g1104 (.A(h_pos[6]),
	.B(n_106),
	.Y(pix_x[6]));
   NOR2BXL g1105 (.AN(v_pos[6]),
	.B(n_100),
	.Y(n_105));
   OR2X1 g1106 (.A(n_113),
	.B(n_102),
	.Y(n_106));
   AOI21XL g1107 (.A0(h_pos[3]),
	.A1(n_116),
	.B0(h_pos[6]),
	.Y(n_104));
   NAND3BXL g1108 (.AN(v_pos[2]),
	.B(n_98),
	.C(n_97),
	.Y(n_103));
   NAND2XL g1109 (.A(h_pos[7]),
	.B(n_96),
	.Y(n_101));
   NOR2BX1 g1110 (.AN(v_pos[6]),
	.B(n_142),
	.Y(n_139));
   NAND2BXL g1111 (.AN(pix_x[10]),
	.B(n_114),
	.Y(n_102));
   AOI21XL g1112 (.A0(v_pos[4]),
	.A1(v_pos[3]),
	.B0(v_pos[5]),
	.Y(n_100));
   NAND2BXL g1113 (.AN(v_pos[9]),
	.B(n_97),
	.Y(pix_y[9]));
   AOI2BB1XL g1114 (.A0N(v_pos[1]),
	.A1N(v_pos[0]),
	.B0(n_143),
	.Y(n_99));
   AND3XL g1115 (.A(h_pos[7]),
	.B(h_pos[6]),
	.C(n_116),
	.Y(n_113));
   NOR2XL g1116 (.A(h_pos[6]),
	.B(h_pos[7]),
	.Y(n_115));
   NAND2XL g1117 (.A(v_pos[8]),
	.B(v_pos[9]),
	.Y(n_140));
   NAND2XL g1118 (.A(v_pos[4]),
	.B(v_pos[5]),
	.Y(n_142));
   NAND2XL g1119 (.A(v_pos[6]),
	.B(v_pos[7]),
	.Y(n_141));
   CLKINVX1 g1120 (.A(n_98),
	.Y(n_144));
   CLKINVX1 g1121 (.A(n_96),
	.Y(n_116));
   NAND2XL g1122 (.A(v_pos[2]),
	.B(v_pos[3]),
	.Y(n_143));
   NAND2XL g1123 (.A(v_pos[1]),
	.B(v_pos[0]),
	.Y(n_98));
   NOR2XL g1124 (.A(pix_x[9]),
	.B(pix_x[8]),
	.Y(n_114));
   NOR2XL g1125 (.A(v_pos[10]),
	.B(v_pos[11]),
	.Y(n_97));
   NAND2XL g1126 (.A(h_pos[5]),
	.B(h_pos[4]),
	.Y(n_96));
   DFFQX1 \h_pos_reg[0]  (.CK(clk),
	.D(n_31),
	.Q(h_pos[0]));
   DFFQX1 \h_pos_reg[1]  (.CK(clk),
	.D(n_30),
	.Q(h_pos[1]));
   DFFQX1 \h_pos_reg[2]  (.CK(clk),
	.D(n_45),
	.Q(h_pos[2]));
   DFFQX1 \h_pos_reg[3]  (.CK(clk),
	.D(n_69),
	.Q(h_pos[3]));
   DFFQX1 \h_pos_reg[4]  (.CK(clk),
	.D(n_80),
	.Q(h_pos[4]));
   DFFQX1 \h_pos_reg[5]  (.CK(clk),
	.D(n_90),
	.Q(h_pos[5]));
   DFFQX1 \h_pos_reg[6]  (.CK(clk),
	.D(n_83),
	.Q(h_pos[6]));
   DFFQX1 \h_pos_reg[7]  (.CK(clk),
	.D(n_91),
	.Q(h_pos[7]));
   DFFQX1 \h_pos_reg[8]  (.CK(clk),
	.D(n_84),
	.Q(pix_x[8]));
   DFFQX1 \h_pos_reg[9]  (.CK(clk),
	.D(n_92),
	.Q(pix_x[9]));
   DFFQX1 \h_pos_reg[10]  (.CK(clk),
	.D(n_145),
	.Q(pix_x[10]));
   SDFFQX1 \v_pos_reg[0]  (.CK(clk),
	.D(n_32),
	.Q(v_pos[0]),
	.SE(v_pos[0]),
	.SI(n_147));
   DFFQX1 \v_pos_reg[1]  (.CK(clk),
	.D(n_50),
	.Q(v_pos[1]));
   DFFQX1 \v_pos_reg[2]  (.CK(clk),
	.D(n_62),
	.Q(v_pos[2]));
   DFFQX1 \v_pos_reg[3]  (.CK(clk),
	.D(n_63),
	.Q(v_pos[3]));
   SDFFQX1 \v_pos_reg[4]  (.CK(clk),
	.D(n_39),
	.Q(v_pos[4]),
	.SE(v_pos[4]),
	.SI(n_41));
   DFFQX1 \v_pos_reg[5]  (.CK(clk),
	.D(n_65),
	.Q(v_pos[5]));
   DFFQX1 \v_pos_reg[6]  (.CK(clk),
	.D(n_51),
	.Q(v_pos[6]));
   DFFQX1 \v_pos_reg[7]  (.CK(clk),
	.D(n_66),
	.Q(v_pos[7]));
   DFFQX1 \v_pos_reg[8]  (.CK(clk),
	.D(n_58),
	.Q(v_pos[8]));
   DFFQX1 \v_pos_reg[9]  (.CK(clk),
	.D(n_59),
	.Q(v_pos[9]));
   DFFQX1 \v_pos_reg[10]  (.CK(clk),
	.D(n_64),
	.Q(v_pos[10]));
   DFFQX1 \v_pos_reg[11]  (.CK(clk),
	.D(n_60),
	.Q(v_pos[11]));
   NOR2XL g1736 (.A(n_23),
	.B(n_88),
	.Y(n_92));
   NOR2XL g1738 (.A(n_23),
	.B(n_89),
	.Y(n_91));
   NOR2XL g1741 (.A(n_23),
	.B(n_82),
	.Y(n_90));
   AOI21X1 g1742 (.A0(h_pos[7]),
	.A1(n_77),
	.B0(n_87),
	.Y(n_89));
   AOI21XL g1743 (.A0(pix_x[9]),
	.A1(n_75),
	.B0(n_86),
	.Y(n_88));
   NOR2XL g1744 (.A(h_pos[7]),
	.B(n_77),
	.Y(n_87));
   NOR2XL g1745 (.A(pix_x[9]),
	.B(n_75),
	.Y(n_86));
   NOR2XL g1747 (.A(n_23),
	.B(n_78),
	.Y(n_84));
   NOR2XL g1748 (.A(n_23),
	.B(n_79),
	.Y(n_83));
   AOI21XL g1749 (.A0(h_pos[5]),
	.A1(n_72),
	.B0(n_81),
	.Y(n_82));
   NOR2XL g1751 (.A(h_pos[5]),
	.B(n_72),
	.Y(n_81));
   NOR2XL g1752 (.A(n_23),
	.B(n_73),
	.Y(n_80));
   AOI21XL g1753 (.A0(h_pos[6]),
	.A1(n_70),
	.B0(n_76),
	.Y(n_79));
   AOI21XL g1754 (.A0(pix_x[8]),
	.A1(n_71),
	.B0(n_74),
	.Y(n_78));
   NOR2XL g1755 (.A(h_pos[6]),
	.B(n_70),
	.Y(n_76));
   NAND2BX1 g1756 (.AN(n_70),
	.B(h_pos[6]),
	.Y(n_77));
   NOR2XL g1758 (.A(pix_x[8]),
	.B(n_71),
	.Y(n_74));
   AOI21XL g1759 (.A0(h_pos[4]),
	.A1(n_49),
	.B0(n_68),
	.Y(n_73));
   NAND2BX1 g1760 (.AN(n_71),
	.B(pix_x[8]),
	.Y(n_75));
   NOR2XL g1768 (.A(n_54),
	.B(n_23),
	.Y(n_69));
   NOR2XL g1769 (.A(h_pos[4]),
	.B(n_49),
	.Y(n_68));
   NAND2XL g1770 (.A(h_pos[4]),
	.B(n_67),
	.Y(n_72));
   NAND2XL g1771 (.A(n_113),
	.B(n_67),
	.Y(n_71));
   NAND2XL g1772 (.A(n_116),
	.B(n_67),
	.Y(n_70));
   CLKINVX1 g1775 (.A(n_49),
	.Y(n_67));
   NAND2XL g1776 (.A(n_40),
	.B(n_53),
	.Y(n_66));
   OAI2BB1X1 g1777 (.A0N(n_0),
	.A1N(n_39),
	.B0(n_52),
	.Y(n_65));
   INVXL g1781 (.A(n_61),
	.Y(n_64));
   OAI21XL g1782 (.A0(n_33),
	.A1(n_20),
	.B0(n_56),
	.Y(n_63));
   OAI2BB1X1 g1783 (.A0N(v_pos[2]),
	.A1N(n_43),
	.B0(n_2),
	.Y(n_62));
   AOI32X1 g1784 (.A0(n_4),
	.A1(n_32),
	.A2(n_27),
	.B0(n_42),
	.B1(v_pos[10]),
	.Y(n_61));
   OAI21XL g1785 (.A0(n_34),
	.A1(n_33),
	.B0(n_55),
	.Y(n_60));
   OAI2BB1X1 g1786 (.A0N(n_32),
	.A1N(n_29),
	.B0(n_57),
	.Y(n_59));
   OAI32X1 g1787 (.A0(v_pos[8]),
	.A1(n_21),
	.A2(n_33),
	.B0(n_5),
	.B1(n_44),
	.Y(n_58));
   NAND2BX1 g1788 (.AN(n_44),
	.B(v_pos[9]),
	.Y(n_57));
   NAND2XL g1789 (.A(v_pos[3]),
	.B(n_43),
	.Y(n_56));
   NAND2XL g1790 (.A(n_42),
	.B(v_pos[11]),
	.Y(n_55));
   AOI21XL g1792 (.A0(h_pos[3]),
	.A1(n_26),
	.B0(n_47),
	.Y(n_54));
   OAI21XL g1793 (.A0(n_36),
	.A1(n_147),
	.B0(v_pos[7]),
	.Y(n_53));
   OAI21X1 g1794 (.A0(n_35),
	.A1(n_146),
	.B0(v_pos[5]),
	.Y(n_52));
   OAI21XL g1795 (.A0(n_33),
	.A1(n_22),
	.B0(n_46),
	.Y(n_51));
   OAI21XL g1796 (.A0(n_33),
	.A1(n_1),
	.B0(n_48),
	.Y(n_50));
   NAND2XL g1797 (.A(v_pos[1]),
	.B(n_146),
	.Y(n_48));
   NOR2XL g1798 (.A(h_pos[3]),
	.B(n_26),
	.Y(n_47));
   NAND2XL g1799 (.A(v_pos[6]),
	.B(n_146),
	.Y(n_46));
   NOR2XL g1800 (.A(n_28),
	.B(n_23),
	.Y(n_45));
   NAND2BX1 g1801 (.AN(n_26),
	.B(h_pos[3]),
	.Y(n_49));
   OAI21X1 g1802 (.A0(n_9),
	.A1(n_33),
	.B0(n_37),
	.Y(n_41));
   NAND3BX1 g1803 (.AN(v_pos[7]),
	.B(n_139),
	.C(n_39),
	.Y(n_40));
   AOI21X1 g1804 (.A0(n_21),
	.A1(n_32),
	.B0(n_146),
	.Y(n_44));
   OAI21X1 g1805 (.A0(n_144),
	.A1(n_33),
	.B0(n_37),
	.Y(n_43));
   OAI21X1 g1806 (.A0(n_33),
	.A1(n_27),
	.B0(n_37),
	.Y(n_42));
   CLKINVX3 g1807 (.A(n_147),
	.Y(n_37));
   NOR2XL g1808 (.A(n_10),
	.B(n_33),
	.Y(n_39));
   AOI21XL g1813 (.A0(n_139),
	.A1(n_9),
	.B0(n_33),
	.Y(n_36));
   AOI21XL g1814 (.A0(v_pos[4]),
	.A1(n_9),
	.B0(n_33),
	.Y(n_35));
   AOI32X1 g1815 (.A0(v_pos[10]),
	.A1(n_6),
	.A2(n_27),
	.B0(v_pos[11]),
	.B1(n_4),
	.Y(n_34));
   CLKINVX1 g1816 (.A(n_33),
	.Y(n_32));
   NOR2XL g1817 (.A(h_pos[0]),
	.B(n_23),
	.Y(n_31));
   NOR2XL g1818 (.A(n_15),
	.B(n_23),
	.Y(n_30));
   NAND2X1 g1819 (.A(n_23),
	.B(n_24),
	.Y(n_33));
   OAI31X1 g1821 (.A0(v_pos[9]),
	.A1(n_5),
	.A2(n_21),
	.B0(n_12),
	.Y(n_29));
   AOI21XL g1822 (.A0(h_pos[2]),
	.A1(n_11),
	.B0(n_25),
	.Y(n_28));
   NOR2XL g1823 (.A(h_pos[2]),
	.B(n_11),
	.Y(n_25));
   NOR2XL g1824 (.A(n_140),
	.B(n_21),
	.Y(n_27));
   NAND2BX1 g1825 (.AN(n_11),
	.B(h_pos[2]),
	.Y(n_26));
   XNOR2XL g1827 (.A(v_pos[6]),
	.B(n_18),
	.Y(n_22));
   NAND4XL g1828 (.A(n_14),
	.B(n_0),
	.C(n_16),
	.D(n_17),
	.Y(n_24));
   AND2X1 g1829 (.A(pix_x[10]),
	.B(n_19),
	.Y(n_23));
   NAND2BX1 g1830 (.AN(n_141),
	.B(n_18),
	.Y(n_21));
   AOI31X1 g1831 (.A0(v_pos[2]),
	.A1(n_7),
	.A2(n_144),
	.B0(n_14),
	.Y(n_20));
   NAND3X1 g1832 (.A(n_13),
	.B(n_115),
	.C(n_114),
	.Y(n_19));
   NOR3X1 g1833 (.A(v_pos[10]),
	.B(v_pos[11]),
	.C(n_12),
	.Y(n_17));
   NOR2XL g1834 (.A(n_142),
	.B(n_10),
	.Y(n_18));
   NOR3X1 g1835 (.A(v_pos[1]),
	.B(v_pos[6]),
	.C(n_8),
	.Y(n_16));
   XNOR2XL g1836 (.A(h_pos[0]),
	.B(h_pos[1]),
	.Y(n_15));
   NOR2XL g1838 (.A(h_pos[4]),
	.B(h_pos[5]),
	.Y(n_13));
   NOR2XL g1840 (.A(v_pos[2]),
	.B(n_7),
	.Y(n_14));
   CLKINVX1 g1841 (.A(n_10),
	.Y(n_9));
   NAND2XL g1842 (.A(v_pos[7]),
	.B(v_pos[0]),
	.Y(n_8));
   NAND2XL g1843 (.A(v_pos[9]),
	.B(n_5),
	.Y(n_12));
   NAND2XL g1844 (.A(h_pos[0]),
	.B(h_pos[1]),
	.Y(n_11));
   NAND2BX1 g1845 (.AN(n_143),
	.B(n_144),
	.Y(n_10));
   CLKINVX1 g1861 (.A(v_pos[3]),
	.Y(n_7));
   INVXL g1868 (.A(v_pos[11]),
	.Y(n_6));
   CLKINVX1 g1875 (.A(v_pos[8]),
	.Y(n_5));
   CLKINVX1 g1878 (.A(v_pos[10]),
	.Y(n_4));
   NAND2BX1 g2 (.AN(n_23),
	.B(n_24),
	.Y(n_3));
   NAND3BX1 g1879 (.AN(v_pos[2]),
	.B(n_144),
	.C(n_32),
	.Y(n_2));
   XNOR2XL g1880 (.A(v_pos[0]),
	.B(v_pos[1]),
	.Y(n_1));
   NOR2BX1 g1881 (.AN(v_pos[4]),
	.B(v_pos[5]),
	.Y(n_0));
   AOI2BB1XL g1883 (.A0N(pix_x[10]),
	.A1N(n_148),
	.B0(n_23),
	.Y(n_145));
   NOR2X4 g1884 (.A(n_3),
	.B(rst),
	.Y(n_146));
   NOR2X6 g1811_dup (.A(n_3),
	.B(rst),
	.Y(n_147));
   NOR2BXL g1885 (.AN(pix_x[9]),
	.B(n_75),
	.Y(n_148));
endmodule

module screen_design (
	clk, 
	rst, 
	h_sync, 
	v_sync, 
	r_out, 
	g_out, 
	b_out);
   input clk;
   input rst;
   output h_sync;
   output v_sync;
   output r_out;
   output g_out;
   output b_out;

   // Internal wires
   wire [11:0] pix_x;
   wire [11:0] pix_y;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;

   assign b_out = 1'b0 ;
   assign g_out = 1'b0 ;

   pixel_itr show (.clk(clk),
	.rst(rst),
	.pix_x({ UNCONNECTED,
		pix_x[10],
		pix_x[9],
		pix_x[8],
		pix_x[7],
		pix_x[6],
		pix_x[5],
		pix_x[4],
		pix_x[3],
		pix_x[2],
		pix_x[1],
		pix_x[0] }),
	.pix_y({ UNCONNECTED1,
		UNCONNECTED0,
		pix_y[9],
		pix_y[8],
		pix_y[7],
		pix_y[6],
		pix_y[5],
		pix_y[4],
		pix_y[3],
		pix_y[2],
		pix_y[1],
		pix_y[0] }),
	.h_sync(h_sync),
	.v_sync(v_sync),
	.draw_active(UNCONNECTED2),
	.screen_end(UNCONNECTED3),
	.draw_end(UNCONNECTED4));
   NOR4BXL g640 (.AN(n_11),
	.B(pix_x[10]),
	.C(n_10),
	.D(n_12),
	.Y(r_out));
   NOR4BXL g641 (.AN(n_9),
	.B(pix_y[0]),
	.C(pix_y[1]),
	.D(pix_y[2]),
	.Y(n_12));
   AOI32XL g642 (.A0(n_6),
	.A1(pix_x[8]),
	.A2(pix_x[9]),
	.B0(n_8),
	.B1(pix_y[9]),
	.Y(n_11));
   AOI211XL g643 (.A0(n_5),
	.A1(n_3),
	.B0(pix_x[8]),
	.C0(pix_x[9]),
	.Y(n_10));
   NOR4BXL g644 (.AN(n_4),
	.B(pix_y[9]),
	.C(pix_y[4]),
	.D(pix_y[6]),
	.Y(n_9));
   AOI21XL g645 (.A0(n_1),
	.A1(n_4),
	.B0(n_7),
	.Y(n_8));
   AOI211XL g646 (.A0(n_0),
	.A1(pix_y[6]),
	.B0(pix_y[8]),
	.C0(pix_y[7]),
	.Y(n_7));
   AO21X1 g647 (.A0(pix_x[3]),
	.A1(n_2),
	.B0(n_5),
	.Y(n_6));
   AND2X1 g648 (.A(pix_x[4]),
	.B(n_2),
	.Y(n_5));
   OR4XL g649 (.A(pix_x[1]),
	.B(pix_x[2]),
	.C(pix_x[0]),
	.D(pix_x[3]),
	.Y(n_3));
   NOR4XL g650 (.A(pix_y[3]),
	.B(pix_y[5]),
	.C(pix_y[8]),
	.D(pix_y[7]),
	.Y(n_4));
   AND3XL g651 (.A(pix_x[6]),
	.B(pix_x[7]),
	.C(pix_x[5]),
	.Y(n_2));
   NAND3XL g652 (.A(pix_y[0]),
	.B(pix_y[1]),
	.C(pix_y[2]),
	.Y(n_1));
   OR2X1 g653 (.A(pix_y[4]),
	.B(pix_y[5]),
	.Y(n_0));
endmodule

