
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov  6 2019 22:05:00 IST (Nov  6 2019 16:35:00 UTC)

// Verification Directory fv/screen_design 

module pixel_itr(clk, pix_clk, rst, pix_x, pix_y, h_sync, v_sync,
     draw_active, screen_end, draw_end);
  input clk, pix_clk, rst;
  output [9:0] pix_x, pix_y;
  output h_sync, v_sync, draw_active, screen_end, draw_end;
  wire clk, pix_clk, rst;
  wire [9:0] pix_x, pix_y;
  wire h_sync, v_sync, draw_active, screen_end, draw_end;
  wire [9:0] v_pos;
  wire [9:0] h_pos;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_85, n_86, n_87, n_110, n_111, n_112;
  wire n_113, n_114;
  NAND3XL g1066(.A (n_76), .B (n_110), .C (n_83), .Y (h_sync));
  NAND4BXL g1067(.AN (v_pos[9]), .B (v_pos[1]), .C (v_pos[3]), .D
       (n_81), .Y (v_sync));
  NOR2BXL g1068(.AN (h_pos[2]), .B (n_82), .Y (pix_x[2]));
  NOR2BXL g1069(.AN (h_pos[6]), .B (n_82), .Y (pix_x[6]));
  NOR2BXL g1070(.AN (h_pos[1]), .B (n_82), .Y (pix_x[1]));
  NOR2BXL g1071(.AN (h_pos[0]), .B (n_82), .Y (pix_x[0]));
  NOR2BXL g1072(.AN (h_pos[3]), .B (n_82), .Y (pix_x[3]));
  NOR2BXL g1073(.AN (h_pos[4]), .B (n_82), .Y (pix_x[4]));
  NOR2BXL g1074(.AN (h_pos[5]), .B (n_82), .Y (pix_x[5]));
  NOR2XL g1075(.A (n_76), .B (n_82), .Y (pix_x[7]));
  AOI211XL g1076(.A0 (n_87), .A1 (n_5), .B0 (pix_x[8]), .C0 (pix_x[9]),
       .Y (n_83));
  NAND2BXL g1077(.AN (v_pos[4]), .B (n_80), .Y (pix_y[4]));
  AND2X1 g1078(.A (v_pos[5]), .B (n_80), .Y (pix_y[5]));
  NAND2BXL g1079(.AN (v_pos[6]), .B (n_80), .Y (pix_y[6]));
  NAND2BXL g1080(.AN (v_pos[3]), .B (n_80), .Y (pix_y[3]));
  NAND2BXL g1081(.AN (v_pos[2]), .B (n_80), .Y (pix_y[2]));
  NAND2BXL g1082(.AN (v_pos[7]), .B (n_80), .Y (pix_y[7]));
  NAND2BXL g1083(.AN (v_pos[0]), .B (n_80), .Y (pix_y[0]));
  NAND2BXL g1084(.AN (v_pos[1]), .B (n_80), .Y (pix_y[1]));
  NOR3BXL g1085(.AN (n_113), .B (n_86), .C (n_79), .Y (n_81));
  AOI211XL g1086(.A0 (n_78), .A1 (h_pos[7]), .B0 (pix_x[8]), .C0
       (pix_x[9]), .Y (n_82));
  NOR2BXL g1087(.AN (n_79), .B (v_pos[9]), .Y (n_80));
  NOR2XL g1088(.A (h_pos[7]), .B (n_78), .Y (n_87));
  NAND2XL g1089(.A (h_pos[6]), .B (n_111), .Y (n_110));
  NOR2XL g1090(.A (n_112), .B (n_77), .Y (n_86));
  NAND3BXL g1091(.AN (n_77), .B (v_pos[5]), .C (v_pos[8]), .Y (n_79));
  OR2XL g1092(.A (h_pos[6]), .B (h_pos[5]), .Y (n_78));
  NAND2XL g1093(.A (v_pos[2]), .B (v_pos[3]), .Y (n_113));
  NAND2XL g1094(.A (v_pos[6]), .B (v_pos[7]), .Y (n_77));
  OR2X1 g1095(.A (v_pos[8]), .B (v_pos[9]), .Y (pix_y[8]));
  NOR2BX1 g1096(.AN (h_pos[6]), .B (n_76), .Y (n_85));
  NOR2BX1 g1097(.AN (h_pos[5]), .B (n_5), .Y (n_111));
  NAND2XL g1098(.A (v_pos[4]), .B (v_pos[5]), .Y (n_112));
  CLKINVX1 g1099(.A (h_pos[7]), .Y (n_76));
  CLKINVX1 g1100(.A (h_pos[4]), .Y (n_5));
  SDFFQX1 \h_pos_reg[0] (.CK (clk), .D (n_52), .SI (n_13), .SE
       (h_pos[0]), .Q (h_pos[0]));
  DFFQX1 \h_pos_reg[1] (.CK (clk), .D (n_61), .Q (h_pos[1]));
  DFFQX1 \h_pos_reg[2] (.CK (clk), .D (n_60), .Q (h_pos[2]));
  DFFQX1 \h_pos_reg[3] (.CK (clk), .D (n_57), .Q (h_pos[3]));
  DFFQX1 \h_pos_reg[4] (.CK (clk), .D (n_62), .Q (h_pos[4]));
  DFFQX1 \h_pos_reg[5] (.CK (clk), .D (n_63), .Q (h_pos[5]));
  DFFQX1 \h_pos_reg[6] (.CK (clk), .D (n_58), .Q (h_pos[6]));
  DFFQX1 \h_pos_reg[7] (.CK (clk), .D (n_59), .Q (h_pos[7]));
  DFFQX1 \h_pos_reg[8] (.CK (clk), .D (n_56), .Q (pix_x[8]));
  DFFQX1 \h_pos_reg[9] (.CK (clk), .D (n_65), .Q (pix_x[9]));
  SDFFQX1 \v_pos_reg[0] (.CK (clk), .D (n_51), .SI (n_64), .SE
       (v_pos[0]), .Q (v_pos[0]));
  DFFQX1 \v_pos_reg[1] (.CK (clk), .D (n_68), .Q (v_pos[1]));
  DFFQX1 \v_pos_reg[2] (.CK (clk), .D (n_69), .Q (v_pos[2]));
  DFFQX1 \v_pos_reg[3] (.CK (clk), .D (n_73), .Q (v_pos[3]));
  DFFQX1 \v_pos_reg[4] (.CK (clk), .D (n_70), .Q (v_pos[4]));
  DFFQX1 \v_pos_reg[5] (.CK (clk), .D (n_74), .Q (v_pos[5]));
  DFFQX1 \v_pos_reg[6] (.CK (clk), .D (n_67), .Q (v_pos[6]));
  DFFQX1 \v_pos_reg[7] (.CK (clk), .D (n_71), .Q (v_pos[7]));
  DFFQX1 \v_pos_reg[8] (.CK (clk), .D (n_66), .Q (v_pos[8]));
  DFFQX1 \v_pos_reg[9] (.CK (clk), .D (n_72), .Q (v_pos[9]));
  AO22XL g1577(.A0 (n_33), .A1 (n_51), .B0 (v_pos[5]), .B1 (n_64), .Y
       (n_74));
  AO22XL g1578(.A0 (n_28), .A1 (n_51), .B0 (v_pos[3]), .B1 (n_64), .Y
       (n_73));
  AO22XL g1579(.A0 (n_36), .A1 (n_51), .B0 (v_pos[9]), .B1 (n_64), .Y
       (n_72));
  AO22XL g1580(.A0 (n_37), .A1 (n_51), .B0 (v_pos[7]), .B1 (n_64), .Y
       (n_71));
  AO22XL g1582(.A0 (n_3), .A1 (n_51), .B0 (v_pos[4]), .B1 (n_64), .Y
       (n_70));
  AO22XL g1583(.A0 (n_25), .A1 (n_51), .B0 (v_pos[2]), .B1 (n_64), .Y
       (n_69));
  AO22XL g1584(.A0 (n_2), .A1 (n_51), .B0 (v_pos[1]), .B1 (n_64), .Y
       (n_68));
  AO22XL g1585(.A0 (n_0), .A1 (n_51), .B0 (v_pos[6]), .B1 (n_64), .Y
       (n_67));
  AO22XL g1586(.A0 (n_32), .A1 (n_51), .B0 (v_pos[8]), .B1 (n_64), .Y
       (n_66));
  OAI22XL g1592(.A0 (n_114), .A1 (n_53), .B0 (n_12), .B1 (n_7), .Y
       (n_65));
  AO22XL g1597(.A0 (n_49), .A1 (n_52), .B0 (h_pos[5]), .B1 (n_13), .Y
       (n_63));
  OAI22X1 g1598(.A0 (n_41), .A1 (n_53), .B0 (n_5), .B1 (n_12), .Y
       (n_62));
  OAI22X1 g1599(.A0 (n_14), .A1 (n_53), .B0 (n_8), .B1 (n_12), .Y
       (n_61));
  NOR2BX2 g1600(.AN (n_55), .B (rst), .Y (n_64));
  OAI22X1 g1601(.A0 (n_19), .A1 (n_53), .B0 (n_9), .B1 (n_12), .Y
       (n_60));
  AO22XL g1602(.A0 (n_44), .A1 (n_52), .B0 (h_pos[7]), .B1 (n_13), .Y
       (n_59));
  AO22XL g1603(.A0 (n_45), .A1 (n_52), .B0 (h_pos[6]), .B1 (n_13), .Y
       (n_58));
  AO22XL g1604(.A0 (n_29), .A1 (n_52), .B0 (h_pos[3]), .B1 (n_13), .Y
       (n_57));
  OAI22X1 g1605(.A0 (n_47), .A1 (n_53), .B0 (n_6), .B1 (n_12), .Y
       (n_56));
  OAI21X1 g1606(.A0 (n_20), .A1 (n_50), .B0 (pix_clk), .Y (n_55));
  CLKINVX1 g1608(.A (n_53), .Y (n_52));
  NAND2BX1 g1609(.AN (n_50), .B (pix_clk), .Y (n_53));
  NOR2BX1 g1610(.AN (n_50), .B (n_23), .Y (n_51));
  AOI211X1 g1611(.A0 (n_87), .A1 (n_38), .B0 (n_7), .C0 (n_6), .Y
       (n_50));
  OAI21XL g1612(.A0 (n_38), .A1 (h_pos[5]), .B0 (n_48), .Y (n_49));
  NAND2XL g1613(.A (h_pos[5]), .B (n_38), .Y (n_48));
  MXI2XL g1614(.A (n_6), .B (pix_x[8]), .S0 (n_42), .Y (n_47));
  NAND2BX1 g1615(.AN (n_42), .B (pix_x[8]), .Y (n_46));
  OAI21XL g1616(.A0 (n_40), .A1 (h_pos[6]), .B0 (n_43), .Y (n_45));
  XOR2XL g1617(.A (h_pos[7]), .B (n_39), .Y (n_44));
  NAND2XL g1618(.A (h_pos[6]), .B (n_40), .Y (n_43));
  MXI2XL g1619(.A (n_5), .B (h_pos[4]), .S0 (n_27), .Y (n_41));
  NAND2BX1 g1620(.AN (n_40), .B (n_85), .Y (n_42));
  NOR2XL g1621(.A (n_110), .B (n_27), .Y (n_39));
  NAND2XL g1622(.A (n_111), .B (n_35), .Y (n_40));
  OAI21X1 g1623(.A0 (v_pos[7]), .A1 (n_26), .B0 (n_34), .Y (n_37));
  XOR2XL g1624(.A (v_pos[9]), .B (n_31), .Y (n_36));
  NAND2XL g1625(.A (h_pos[4]), .B (n_35), .Y (n_38));
  CLKINVX1 g1626(.A (n_27), .Y (n_35));
  NAND2XL g1627(.A (v_pos[7]), .B (n_26), .Y (n_34));
  OAI21X1 g1628(.A0 (v_pos[5]), .A1 (n_22), .B0 (n_30), .Y (n_33));
  ADDHX1 g1629(.A (v_pos[8]), .B (n_21), .CO (n_31), .S (n_32));
  NAND2XL g1630(.A (v_pos[5]), .B (n_22), .Y (n_30));
  CLKXOR2X1 g1631(.A (h_pos[3]), .B (n_18), .Y (n_29));
  CLKXOR2X1 g1632(.A (v_pos[3]), .B (n_24), .Y (n_28));
  NAND2XL g1633(.A (h_pos[3]), .B (n_18), .Y (n_27));
  ADDHX1 g1635(.A (v_pos[2]), .B (n_15), .CO (n_24), .S (n_25));
  NAND2XL g1636(.A (v_pos[6]), .B (n_4), .Y (n_26));
  NAND2BX1 g1637(.AN (n_20), .B (pix_clk), .Y (n_23));
  NAND2XL g1639(.A (v_pos[4]), .B (n_17), .Y (n_22));
  AND2X1 g1640(.A (n_86), .B (n_17), .Y (n_21));
  MXI2XL g1641(.A (n_9), .B (h_pos[2]), .S0 (n_11), .Y (n_19));
  NOR4BX1 g1642(.AN (n_16), .B (v_pos[6]), .C (v_pos[8]), .D (n_1), .Y
       (n_20));
  NOR2XL g1644(.A (n_9), .B (n_11), .Y (n_18));
  NOR4BX1 g1646(.AN (v_pos[2]), .B (v_pos[4]), .C (v_pos[0]), .D
       (v_pos[1]), .Y (n_16));
  NOR2XL g1647(.A (n_113), .B (n_10), .Y (n_17));
  CLKINVX1 g1648(.A (n_10), .Y (n_15));
  MXI2XL g1651(.A (h_pos[1]), .B (n_8), .S0 (h_pos[0]), .Y (n_14));
  CLKINVX1 g1652(.A (n_13), .Y (n_12));
  NOR2X2 g1653(.A (pix_clk), .B (rst), .Y (n_13));
  NAND2XL g1654(.A (h_pos[0]), .B (h_pos[1]), .Y (n_11));
  NAND2XL g1655(.A (v_pos[0]), .B (v_pos[1]), .Y (n_10));
  CLKINVX1 g1657(.A (h_pos[2]), .Y (n_9));
  CLKINVX1 g1658(.A (h_pos[1]), .Y (n_8));
  CLKINVX1 g1671(.A (pix_x[9]), .Y (n_7));
  CLKINVX1 g1682(.A (pix_x[8]), .Y (n_6));
  NOR2BX1 g2(.AN (n_17), .B (n_112), .Y (n_4));
  XOR2XL g1683(.A (v_pos[4]), .B (n_17), .Y (n_3));
  XOR2XL g1684(.A (v_pos[0]), .B (v_pos[1]), .Y (n_2));
  NAND4BBXL g1685(.AN (v_pos[5]), .BN (v_pos[7]), .C (v_pos[3]), .D
       (v_pos[9]), .Y (n_1));
  XOR2XL g1686(.A (v_pos[6]), .B (n_4), .Y (n_0));
  NOR2BXL g1687(.AN (n_46), .B (pix_x[9]), .Y (n_114));
endmodule

module screen_design(clk, rst, h_sync, v_sync, r_out, g_out, b_out,
     temp);
  input clk, rst;
  output h_sync, v_sync, r_out, g_out, b_out, temp;
  wire clk, rst;
  wire h_sync, v_sync, r_out, g_out, b_out, temp;
  wire [9:0] pix_x;
  wire [8:0] pix_y;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, count,
       n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  pixel_itr show(.clk (clk), .pix_clk (temp), .rst (rst), .pix_x
       (pix_x), .pix_y ({UNCONNECTED, pix_y}), .h_sync (h_sync),
       .v_sync (v_sync), .draw_active (UNCONNECTED0), .screen_end
       (UNCONNECTED1), .draw_end (UNCONNECTED2));
  DFFQX1 count_reg(.CK (clk), .D (n_26), .Q (count));
  DFFQX1 pix_clk_reg(.CK (clk), .D (count), .Q (temp));
  INVXL g936(.A (n_25), .Y (r_out));
  AOI31XL g937(.A0 (n_20), .A1 (n_17), .A2 (pix_x[8]), .B0 (n_23), .Y
       (n_25));
  NOR2XL g938(.A (pix_y[8]), .B (n_24), .Y (b_out));
  AO21X1 g939(.A0 (n_20), .A1 (n_22), .B0 (n_23), .Y (g_out));
  NAND3XL g940(.A (pix_x[8]), .B (n_17), .C (n_19), .Y (n_24));
  NOR3BXL g941(.AN (n_19), .B (pix_y[8]), .C (n_21), .Y (n_23));
  CLKINVX1 g942(.A (n_21), .Y (n_22));
  NAND2XL g943(.A (pix_x[8]), .B (n_18), .Y (n_21));
  NOR4XL g944(.A (pix_y[8]), .B (pix_y[7]), .C (n_14), .D (n_15), .Y
       (n_20));
  OAI21XL g945(.A0 (n_13), .A1 (pix_y[6]), .B0 (n_16), .Y (n_19));
  AOI211XL g946(.A0 (n_1), .A1 (pix_x[7]), .B0 (pix_x[9]), .C0 (n_12),
       .Y (n_18));
  NAND4XL g947(.A (pix_y[4]), .B (pix_y[6]), .C (pix_y[5]), .D (n_11),
       .Y (n_16));
  NOR4BXL g948(.AN (n_7), .B (pix_x[9]), .C (pix_x[7]), .D (pix_x[6]),
       .Y (n_17));
  AOI21XL g949(.A0 (pix_y[5]), .A1 (n_10), .B0 (pix_y[6]), .Y (n_15));
  NOR2BXL g950(.AN (pix_y[6]), .B (n_9), .Y (n_14));
  NAND2XL g951(.A (pix_y[7]), .B (n_8), .Y (n_13));
  MX2X1 g952(.A (n_6), .B (n_0), .S0 (pix_x[6]), .Y (n_12));
  NOR2XL g953(.A (pix_y[7]), .B (n_5), .Y (n_11));
  NAND2BXL g954(.AN (pix_y[4]), .B (n_5), .Y (n_10));
  AOI21XL g955(.A0 (pix_y[4]), .A1 (n_4), .B0 (pix_y[5]), .Y (n_9));
  OAI21XL g956(.A0 (n_4), .A1 (pix_y[4]), .B0 (pix_y[5]), .Y (n_8));
  NAND3XL g957(.A (pix_x[4]), .B (pix_x[5]), .C (n_3), .Y (n_7));
  NAND2BXL g958(.AN (n_3), .B (pix_x[7]), .Y (n_6));
  OAI21XL g959(.A0 (n_2), .A1 (pix_y[0]), .B0 (pix_y[3]), .Y (n_5));
  AND2X1 g960(.A (pix_y[3]), .B (n_2), .Y (n_4));
  OR4X1 g961(.A (pix_x[3]), .B (pix_x[1]), .C (pix_x[2]), .D
       (pix_x[0]), .Y (n_3));
  OR2X1 g962(.A (pix_y[2]), .B (pix_y[1]), .Y (n_2));
  INVXL g963(.A (n_0), .Y (n_1));
  NOR2XL g964(.A (pix_x[5]), .B (pix_x[4]), .Y (n_0));
  INVXL g965(.A (count), .Y (n_26));
endmodule

